<<<<<<< HEAD
﻿//308
=======
﻿//333
>>>>>>> refs/remotes/SEServerExtender/master
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

<<<<<<< HEAD
[assembly: AssemblyFileVersion("1.13.5.308")]
[assembly: AssemblyVersion("1.13.5.308")]
=======
[assembly: AssemblyFileVersion("1.13.5.333")]
[assembly: AssemblyVersion("1.13.5.333")]
>>>>>>> refs/remotes/SEServerExtender/master
